### PR TITLE
preparing for Xcode 9

### PR DESCRIPTION
**Pull request by Maryom**

### CODE REVIEW

**Comment by Mazyod** [comment]
Seems like the tests need to be updated

**Comment by Maryom** [comment]
Ok.

**Comment by Maryom** [comment]
Kindly check these:

In `testAngle()` I changed it as follow:

```
let vector90 = CGVector(dx: 0, dy: 20)
        XCTAssertEqual(vector90.angle, .pi/2, accuracy: accuracy)
```

In `testNegativeInsets()` I changed it as follow:

```
func testNegativeInsets() {
        
        let rect = CGRect(x: -10, y: -10, width: 20, height: 20)
        let newRect = rect.insetEdges(left: 0, right: 0)

        rect.insetBy(dx: -5, dy: 0)
        
        XCTAssertEqual(rect, newRect)
    }
```

**Comment by Mazyod** [comment]
👏  perfect, thanks

**Comment by Maryom** [comment]
You are welcome. What else Ktiz's repositories need to update them ?

**Pull request merged**
